### ISSUE TITLE
Zonemod: Don't give pills after round start

### ISSUE THREAD

**Issue by AshesBeneath** [SirPlease/Server4Dead-Project#5]
Tried adding "confogl_addcvar starting_item_flags 4" in zonemod.cfg but didn't work also pills don't spawn outside saferoom too. (even it's limit was set in the cfg files.)
Didn't changed anything in your code except the one above.
What do i need to do?

**Comment by SirPlease** [comment]
Hi Ashes,

Pills are supposed to be given when the Survivors leave the saferoom, they're not in the saferoom area on the ground.
If you're saying that Survivors are not getting pills automatically, then it looks like you've missed a crucial part of your setup.

In the above case, I believe it was caused because of an incompatible Sourcemod version (assuming you didn't do anything wrong regarding the installation of the plugins and haven't messed with the cfgfiles)
If you want everything to work smoothly, I recommend using the version provided in this Repo.

**Comment by AshesBeneath** [comment]
Hi Sir,

Sorry for late reply. (You answered quicker than I expect xD) My host is using the latest Sourcemod (version 1.8.0), that's might be the problem i guess so. Unfortunately my host doesn't let me write on the sourcemod core files in "bin" folder, so is there any other way to resolve this incompatibility issue?
Will it work if I compile the source files of plugins in question (from Attano's Competitive Framework repo) with the current sourcemod i have?
Even it won't work, I think I can fix the starting pills problem by just getting medkits back and replacing them with pills, but I don't know what to do with not spawning outside of saferooms.

**Comment by SirPlease** [comment]
You can attempt recompiling the plugin, I do think there's multiple plugins that require a recompile or simply don't work on newer (1.8 and above) Sourcemod installs however. You'd have to keep an eye on that.

**Comment by AshesBeneath** [comment]
Seem to not work, I guess I will ask my host to replace sourcemod with the one you provided in the repo. Anyways thanks for your support Sir.
